default: &default
  adapter: postgresql
  encoding: unicode
  username: gschool
  pool: 5

development:
  <<: *default
  database: lukefolio_development

test:
  <<: *default
  database: lukefolio_test
