default: &default
  adapter: postgresql
  encoding: unicode
  username: lemccomb

development:
  <<: *default
  database: lukefolio_development

test:
  <<: *default
  database: lukefolio_test

production:
  <<: *default
  database: lukefolio_production
  username: lemccomb
  password: <%= ENV['LUKEMCCOMB_DATABASE_PASSWORD'] %>
